# Generated by Django 5.1.6 on 2025-02-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_total_cost_orderitem_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_addresses',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice_address',
        ),
    ]
